name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2

      - name: Set up Node.js (for example if you are using a JavaScript-based build)
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug - List files
        run: ls -la ./

      - name: Debug - List /dist files
        run: ls -la ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          publish_dir: ./../dist
          publish_branch: gh-pages
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
